src/Entity/Article.php
<?php

namespace App\Entity;

use App\Repository\ArticleRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Gedmo\Mapping\Annotation as Gedmo;
use Gedmo\Timestampable\Traits\TimestampableEntity;
use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Component\Validator\Context\ExecutionContextInterface;

/**
 * @ORM\Entity(repositoryClass=ArticleRepository::class)
 * @Assert\EnableAutoMapping()
 */
class Article
{
    use TimestampableEntity;
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private int $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Поле заголовок не должно быть пустым")
     */
    private ?string $title = null;

    /**
     * @Gedmo\Slug(fields={"title"})
     * @ORM\Column(type="string", length=100, unique=true)
     * @Assert\DisableAutoMapping()
     */
    private ?string $slug;

    /**
     * @ORM\Column(type="text", nullable=true)
     * @Assert\NotBlank(message="Поле тело обязательно для заполнения")
     */
    private ?string $body;

    /**
     * @ORM\Column(type="datetime_immutable", nullable=true)
     */
    private ?\DateTimeImmutable $publishedAt;

    /**
     * @ORM\Column(type="string", length=256, nullable=true)
     */
    private ?string $image;

    /**
     * @ORM\Column(type="integer", nullable=false,)
     */
    private ?int $voteCount = 0;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private ?string $keywords;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private ?string $description;

    /**
     * @ORM\OneToMany(targetEntity=Comment::class, mappedBy="article", fetch="EXTRA_LAZY" )
     * @ORM\OrderBy({"createdAt" = "DESC"})
     */
    public ?Collection $comments = null;

    /**
     * @ORM\ManyToMany(targetEntity=Tag::class, inversedBy="articles")
     */
    private  Collection $tags;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="articles")
     * @ORM\JoinColumn(nullable=false)
     */
    private ?User $author;

    /**
     * @var \DateTime
     * @Gedmo\Timestampable(on="create")
     * @ORM\Column(type="datetime")
     * @Assert\DisableAutoMapping()
     */
    protected $createdAt;

    /**
     * @var \DateTime
     * @Gedmo\Timestampable(on="update")
     * @ORM\Column(type="datetime")
     * @Assert\DisableAutoMapping()
     */
    protected $updatedAt;

    public function __construct()
    {
        $this->comments = new ArrayCollection();
        $this->tags = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getBody(): ?string
    {
        return $this->body;
    }

    public function setBody(?string $body): self
    {
        $this->body = $body;

        return $this;
    }

    public function getPublishedAt(): ?\DateTimeImmutable
    {
        return $this->publishedAt;
    }

    public function setPublishedAt(?\DateTimeInterface $publishedAt): self
    {
        $this->publishedAt = $publishedAt;

        return $this;
    }

    /**
     * @return string|null
     */
    public function getImage(): ?string
    {
        return $this->image;
    }

    /**
     * @param string|null $image
     * @return Article
     */
    public function setImage(?string $image): self
    {
        $this->image = $image;

        return $this;
    }

    /**
     * @param int|null $voteCount
     * @return Article
     */
    public function setVoteCount(?int $voteCount): self
    {
        $this->voteCount = $voteCount;

        return $this;
    }

    /**
     * @return int|null
     */
    public function getVoteCount(): ?int
    {
        return $this->voteCount;
    }

    public function getImagePath(): string
    {
        return 'images/'. $this->getImage();
    }

    public function getAuthorAvatarPath(): string
    {
        return sprintf("https://robohash.org/%s.png?set=set3", str_replace(' ', '_', $this->getAuthor()));
    }

    public function voteUp(): Article
    {
        $this->voteCount++;
        return $this;
    }
    public function voteDown(): Article
    {
        $this->voteCount--;
        return $this;
    }

    public function getKeywords(): ?string
    {
        return $this->keywords;
    }

    public function setKeywords(?string $keywords): self
    {
        $this->keywords = $keywords;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getComments(): Collection
    {
        return $this->comments;
    }

    /**
     * @return Collection|Comment[]
     */
    public function getNonDeletedComments(): Collection
    {
        return $this->comments;
    }

    public function addComments($comments): self
    {
        foreach ($comments as $comment)
        {
            $this->addComment($comment);
        }

        return $this;
    }

    public function addComment(Comment $comment): self
    {
        if (!$this->comments->contains($comment)) {
            $this->comments[] = $comment;
            $comment->setArticle($this);
        }

        return $this;
    }

    public function removeComment(Comment $comment): self
    {
        if ($this->comments->removeElement($comment)) {
            // set the owning side to null (unless already changed)
            if ($comment->getArticle() === $this) {
                $comment->setArticle(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Tag[]
     */
    public function getTags(): Collection
    {
        return $this->tags;
    }

    public function addTag(Tag $tag): self
    {
        if (!$this->tags->contains($tag)) {
            $this->tags[] = $tag;
        }

        return $this;
    }

    public function removeTag(Tag $tag): self
    {
        $this->tags->removeElement($tag);

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function isPublished(): bool
    {
        return !is_null($this->getPublishedAt());
    }

    /**
     * @param ExecutionContextInterface $context
     * @param $payload
     * @Assert\Callback()
     */
    public function validate(ExecutionContextInterface $context, $payload)
    {
        if (mb_stripos($this->getTitle(), 'собак') !== false) {
            $context->buildViolation('Про собак писать запрещено')
                ->atPath('title')
                ->addViolation();
        }
    }
}

src/Controller/Admin/ArticlesController.php
<?php

namespace App\Controller\Admin;

use App\Entity\Article;
use App\Entity\User;
use App\Form\ArticleFormType;
use App\Repository\IArticleRepository;
use App\Repository\ICommentRepository;
use Doctrine\ORM\EntityManagerInterface;
use Exception;
use Knp\Component\Pager\PaginatorInterface;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\IsGranted;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\String\Slugger\SluggerInterface;

/**
 * Class ArticlesController
 * @package App\Controller\Admin
 * @method User|null getUser()
 */
class ArticlesController extends AbstractController
{
    /**
     * @Route("/admin/articles", name="app_admin_articles_list")
     * @IsGranted("ROLE_ADMIN_ARTICLE"))
     * @throws Exception
     */
    public function index(
        Request $request,
        IArticleRepository $articleRepository,
        PaginatorInterface $paginator
    ): Response {
        $pagination = $paginator->paginate(
            $articleRepository->latest(),
            $request->query->getInt('page', 1),
            10
        );

        return $this->render("admin/articles/article.index.html.twig", ['pagination' => $pagination]);
    }

    /**
     * @Route("/admin/articles/create", name="app_admin_articles_create")
     * @IsGranted("ROLE_ADMIN_ARTICLE")
     * @throws Exception
     */
    public function create(Request $request, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(ArticleFormType::class);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var Article $article */
            $article = $form->getData();

            $entityManager->persist($article);
            $entityManager->flush();

            $this->addFlash('flash_message', 'Статья успешно создана');
            return $this->redirectToRoute('app_admin_articles_list');
        }

        return $this->render(
            "admin/articles/article.create.html.twig",
            ['articleForm' => $form->createView(), 'showError' => !$form->getErrors()]
        );
    }

    /**
     * @Route("/admin/articles/{id}/edit", name="app_admin_articles_edit")
     * @IsGranted("MANAGE", subject="article")
     * @throws Exception
     */
    public function edit(
        Article $article,
        Request $request,
        EntityManagerInterface $entityManager,
        ICommentRepository $commentRepository,
        SluggerInterface $slugger

    ): Response {
        $form = $this->createForm(ArticleFormType::class, $article, ['enabled_published_at' => true]);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var Article $article */
            $article = $form->getData();

            /** @var UploadedFile|null $image */
            $image = $form->get('image')->getData();

            $fileName = $slugger
                ->slug(pathinfo($image->getClientOriginalName(), PATHINFO_FILENAME))
                ->append('-' . uniqid())
                ->append('.' . $image->guessExtension())
                ->toString();

            $newFile =  $image->move($this->getParameter('article_uploads_dir'), $fileName);
            $article->setImage($newFile->getFilename());

            $entityManager->persist($article);
            $entityManager->flush();

            $this->addFlash('flash_message', 'Статья успешно изменена');
            return $this->redirectToRoute('app_admin_articles_edit', ['id' => $article->getId()]);
        }


        return $this->render(
            "admin/articles/article.edit.html.twig",
            [
                'articleForm' => $form->createView(),
                'showError' => !$form->getErrors(),
                'comments' => $commentRepository->findAll()
            ]
        );
    }
}

src/Controller/Api/ArticleController.php
<?php

namespace App\Controller\Api;

use App\Entity\Article;
use App\Services\IArticleContentProvider;
use Doctrine\ORM\EntityManagerInterface;
use Psr\Log\LoggerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpKernel\Exception\NotFoundHttpException;
use Symfony\Component\Routing\Annotation\Route;


/**
 * Class ArticleController
 * @package App\Controller\Api
 */
class ArticleController extends AbstractController
{
    public const VOTE_TYPE_UP = 'up';
    /**
     * @var IArticleContentProvider
     */
    private IArticleContentProvider $articleContentProvider;

    public function __construct(IArticleContentProvider $articleContentProvider)
    {
        $this->articleContentProvider = $articleContentProvider;
    }

    /**
     * @Route("/api/article", name="api_article", methods={"POST"})
     * @param Request $request
     * @return Response
     */
    public function getText(Request $request): Response
    {
        $countParagraphs = $request->get('countParagraphs');

        if ($countParagraphs > 25) {
            throw new NotFoundHttpException("The maximum number of paragraphs is 25");
        }

        $word = $request->get('word') ?? null;
        $wordsCount = $request->get('wordsCount') ?? 0;

        $text = $this->articleContentProvider->get($countParagraphs, $word, $wordsCount);
        return new JsonResponse(['text' => $text], 200, ['Content-Type' => 'application/json; charset=utf-8']);
    }

    /**
     * @param Article $article
     * @param string $type
     * @param LoggerInterface $logger
     * @param EntityManagerInterface $entityManager
     * @return JsonResponse
     * @Route("articles/{slug}/vote/{type<up|down>}", name="vote", methods={"POST"})
     */
    public function vote(Article $article, string $type, LoggerInterface $logger, EntityManagerInterface $entityManager): Response
    {
        if ($type === static::VOTE_TYPE_UP) {
            $article->voteUp();
        } else {
            $article->voteDown();
        }

        $entityManager->flush();
        return $this->json(['voteCount' => $article->getVoteCount()]);
    }
}

templates/articles/article_content.html.twig
{% extends 'base_conent.html.twig' %}

{% block content %}
<div class="col-12">
    <div class="border flex-md-row mb-4 shadow-sm bg-white p-4">
        <form>
            <div class="form-group">
                <label>Количество параграфов</label>
                <input type="number" class="form-control" name="countParagraphs" value="{{ app.request.get('countParagraphs') }}">
            </div>
            <div class="form-group">
                <label>Вставляемое слово</label>
                <input type="text" class="form-control" name="word" value="{{ app.request.get('word') }}">
            </div>
            <div class="form-group">
                <label>Количество повторений вставляемого слова</label>
                <input type="number" class="form-control"  name="wordsCount" value="{{ app.request.get('wordsCount') }}">
            </div>
            <br>
            <button type="submit" class="btn btn-primary">Сгенерировать текст</button>
        </form>
    </div>
    {% if text %}
        <div class="col-12 mt-2 mb-4">
            <p>{{ text|cached_markdown }}</p>
        </div>
    {% endif %}
</div>
{% endblock %}

templates/articles/view.html.twig
{% extends 'base_conent.html.twig' %}

{% block title %} {{ article.title }} - Spill-Coffee-On-The-Keyboard {% endblock %}
{% block head %}
    {% if  article.keywords  %}
        <meta name="Keywords" content="{{ article.keywords }}">
    {% endif  %}
    {{ parent() }}
{% endblock %}

{% block content_row_class %} no-gutters featured-border{% endblock %}
{% block content_col_class %} article-detail{% endblock %}

{% block content %}
    <div class="col-sm-12 p-2">
        <div class="media d-flex align-content-center">
            <img class="article-detail-image align-self-start mr-3 rounded" src="{{ uploaded_asset('article_uploads', article.image) }}" href="{{ path('app_homepage') }}">
            <div class="media-body d-inline-block align-self-center">
                <h1 class="mb-2">{{ article.title | raw}}</h1>
                <div class="d-flex mb-2">
                    <div class="text-muted align-self-center">
                        <img class="article-author-img rounded-circle mr-2" src="{{ article.author.urlAvatar }}">
                        {{ article.author.firstName }}
                    </div>
                    <div class="text-muted align-self-center ml-4"><i class="fas fa-clock size-is-"></i>
                        {{ article.publishedAt ? article.publishedAt|ago : 'Неопубликована' }}
                    </div>
                </div>
                {% include 'partial/article_tags.html.twig' with {tags: article.tags} %}
                <div class="mb-2">
                    <div class="text-muted align-self-center article-detail-arrows">
                        <span data-item="voteCount" {% if article.voteCount != 0 %}class="{{ article.voteCount > 0 ? "text-success" : "text-danger" }}{% endif %}">{{ article.voteCount }}</span>
                        <button class="btn btn-success ml-3" data-item="votesButton" data-url="{{ path('vote', {'slug': article.slug, 'type' : 'up'}) }}"><i class="fas fa-arrow-up"></i></button>
                        <button class="btn btn-danger" data-item="votesButton" data-url="{{ path('vote', {'slug': article.slug, 'type' : 'down'}) }}"><i class="fas fa-arrow-down"></i></button>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="col-12 mt-2 mb-4">
        <p>{{ article.body|cached_markdown }}</p>
    </div>
    <div class="col-sm-12 mb-4">
        <h3><i class="pr-3 far fa-comment text-secondary"></i>{{ article.nonDeletedComments|length }} Комментария</h3>
        <hr>
        <div class="row mb-4">
            <div class="col-sm-12">
                <div class="comment-container align-self-start col-sm-6">
                    <div class="form-group">
                        <textarea class="form-control" rows="2"></textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">Комментировать</button>
                </div>
            </div>
        </div>

        {% for comment in article.nonDeletedComments %}
            <div class="row mt-2">
                <div class="col-sm-12">
                    <div class="media">
                        <img class="align-self-start comment-img rounded-circle" src="{{ asset('images/profile.png') }}">
                        <div class="media-body align-self-start col-sm-6">
                            <b>{{ comment.authorName }}</b>
                            <small>{{ comment.createdAt|ago }} {% if comment.deletedAt %}DELETED{% endif %}</small>
                            <br>
                            <span class="comment">{{ comment.content }}</span>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
{% endblock %}